### ISSUE TITLE
prevent page refresh on F5

### ISSUE THREAD

**Issue by henrikgebauer** [crocopaw/teka-teki#57]
I like to set the colors with the F-keys, for example F6 for green. Going back to black is on the F5-key.
If I accidentaly hit F4 I get to the instructions. I happened more than once to me that I pressed "F5" right afterwards out of an impulse to correct my error of using the wrong key. But in that case (instructions open) the puzzle will reload.

The F5 key should be ignored in that case or even send me back to the puzzle.

**Comment by crocopaw** [comment]
At the moment, the applet sends als unused keystrokes to the browser. In some cases, that behavior sees not apropriate, e.g. with F5 as mentioned, or with backspace. In the beginning I had alle keys captured, which caused problems too. I'll have to rethink about this.

**Comment by crocopaw** [comment]
Fixed. I hope, that no new problems will creep up, with this new version.
